#!/usr/bin/env python3
import subprocess
import os

subprocess.run("wget https://sourceforge.net/projects/lemur/files/lemur/indri-5.13/indri-5.13.tar.gz".split())

os.mkdir("/work/Indri-src")

subprocess.run("tar -xvzf indri-5.13.tar.gz -C /work".split())

os.chdir("/work/indri-5.13/")

#compile Indri
subprocess.run("./configure --prefix=/work/Indri".split())
subprocess.run("make")
subprocess.run("make install".split())
